{
 "title": "FoodParser",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Base Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Handled Database",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SELECT COUNT(*) FROM statistic) / ((SELECT COUNT(*) FROM category) / 100) AS percent_parsed"
    }
   ]
  },
  {
   "title": "Handled Categories",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), (SELECT COUNT(*) FROM FoodstuffStorage.category) AS `Max` FROM FoodstuffStorage.statistic WHERE status='done'"
    }
   ]
  },
  {
   "title": "In Progress Task",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT store_id AS `Store ID`, category_id AS `Category ID`, last_product_ean AS `Product EAN`, num_paginator_page AS `Paginator Page` FROM FoodstuffStorage.statistic WHERE status='in progress'"
    }
   ]
  },
  { "title": "Foodstuffs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Foddstuffs (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ean) AS `Total` FROM product WHERE energy != ''"
    }
   ]
  },
  {
   "title": "Foddstuffs (Unique)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT ean) AS `Unique` FROM product WHERE energy != ''"
    }
   ]
  },
  {
   "title": "Unique Foodstuffs Percent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(DISTINCT ean) / (COUNT(ean) / 100) AS percent_parsed\nFROM product WHERE energy != '';"
    }
   ]
  },
  { "title": "Products", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Products (Total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(ean) AS `Total`\nFROM product;"
    }
   ]
  },
  {
   "title": "Products (Unique)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(DISTINCT ean) AS `Unique`\nFROM product;"
    }
   ]
  },
  {
   "title": "Unique Products Percent",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(DISTINCT ean) / (COUNT(ean) / 100) AS percent_parsed\nFROM product;"
    }
   ]
  }
 ]
}